name: elite_edge_labs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  dropdown_search: ^5.0.6
  flutter_spinkit: ^5.2.1
  foundation: ^0.0.5
  go_router: ^14.2.7
  get: ^4.6.6
  gap: ^3.0.1
  firebase_auth: ^5.2.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
 
  uses-material-design: true
