// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhoAhc2Ut3Lo0tL4a_WunYhIR5PPAUZI',
    appId: '1:910353541716:web:112f0bc879b0ec1f061bc1',
    messagingSenderId: '910353541716',
    projectId: 'eliteedge-labs',
    authDomain: 'eliteedge-labs.firebaseapp.com',
    storageBucket: 'eliteedge-labs.appspot.com',
    measurementId: 'G-9R1FN4RPFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6BSs_aRKUnHu50Sc5P7aZGv72PPM5yE',
    appId: '1:910353541716:android:38159d54e950bd78061bc1',
    messagingSenderId: '910353541716',
    projectId: 'eliteedge-labs',
    storageBucket: 'eliteedge-labs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCmyouvMT8eC3chifqJ1HgiPa-k3U0gis',
    appId: '1:910353541716:ios:d2d125299d6935b8061bc1',
    messagingSenderId: '910353541716',
    projectId: 'eliteedge-labs',
    storageBucket: 'eliteedge-labs.appspot.com',
    iosBundleId: 'com.example.eliteEdgeLabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCmyouvMT8eC3chifqJ1HgiPa-k3U0gis',
    appId: '1:910353541716:ios:d2d125299d6935b8061bc1',
    messagingSenderId: '910353541716',
    projectId: 'eliteedge-labs',
    storageBucket: 'eliteedge-labs.appspot.com',
    iosBundleId: 'com.example.eliteEdgeLabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAhoAhc2Ut3Lo0tL4a_WunYhIR5PPAUZI',
    appId: '1:910353541716:web:32d99681481a3e4a061bc1',
    messagingSenderId: '910353541716',
    projectId: 'eliteedge-labs',
    authDomain: 'eliteedge-labs.firebaseapp.com',
    storageBucket: 'eliteedge-labs.appspot.com',
    measurementId: 'G-9E7EQLC9JY',
  );
}
